language: python
python:
  - 2.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install -qq python-numpy python-scipy

install:
  - yes | python setup.py install

before_script:
  - python --version

# command to run tests, e.g. python setup.py test
script: cd test; python test_all.py

branches:
  only:
    - master

#The email defaults are too talkative while we're getting Travis working nicely.
notifications:
  email: false