language: python
python:
  - 2.6
  - 2.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - sudo apt-get install python-scipy python-numpy
install:
  - cd src
  - /usr/bin/yes | sudo python setup.py build 2>&1 | tail
  - /usr/bin/yes | sudo python setup.py install 2>&1 | tail
  - cd ..

before_script:
  - python --version

# command to run tests, e.g. python setup.py test
script: cd test; python test_all.py

branches:
  only:
    - master

#The email defaults are too talkative while we're getting Travis working nicely.
notifications:
  email: false