BootStrap: docker
From:neurodebian:jessie

%help
  minimal TADbit container

%environment
  LANG=C.UTF-8 
  LC_ALL=C.UTF-8
  PATH="/usr/local/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  export PATH LANG LC_ALL

%post

  # for R
  echo "deb-src ftp://ftp.de.debian.org/debian/ jessie main contrib" >> /etc/apt/sources.list

  apt-get update --fix-missing

  apt-get -y build-dep libxml2-dev
  apt-get -y build-dep libcurl4-gnutls-dev
  apt-get -y install dirmngr libcurl4-gnutls-dev

  # apt install utilities
  apt-get update --fix-missing && \
  apt-get install -y unzip build-essential wget bzip2 --no-install-recommends

  #############################################################################
  # conda
  echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
  wget --quiet --no-check-certificate https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh \
      -O $HOME/miniconda.sh
  /bin/bash $HOME/miniconda.sh -b -p /usr/local/anaconda
  rm $HOME/miniconda.sh
  
  export PATH="/usr/local/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  conda config --set always_yes yes --set changeps1 no
  conda update -q conda
  conda info -a

  #############################################################################
  # install python packages and R
  conda config --add channels salilab && conda config --add channels bioconda && \
  conda config --add channels hargup/label/pypi && \
  conda install -y -q imp scipy matplotlib jupyter mcl samtools sra-tools pysam pebble && \
  conda install -y -q -c r r && \
  conda install -y -q -c bioconda ucsc-bigWigToBedGraph
  conda install -c bioconda ucsc-wigtobigwig
  # to run jupyter the notebok has to be built and installed as writable (with sudo)
  # conda install -y -q jupyter
  conda clean -y --all  && rm -rf /opt/conda/pkgs/*

  #############################################################################
  # dryhic
  R --slave -e 'install.packages("devtools", repos="http://cran.rstudio.com/")'
  R --slave -e 'options(repos="http://cran.rstudio.com/"); devtools::install_github("qenvio/dryhic")'

  #############################################################################
  # GEM
  wget --quiet --no-check-certificate https://sourceforge.net/projects/gemlibrary/files/gem-library/Binary%20pre-release%203/GEM-binaries-Linux-x86_64-core_i3-20130406-045632.tbz2/download -O GEM.tbz2 && \
  tar -xvjf GEM.tbz2 && \
  rm -f GEM-binaries-*/bin/LICENCE && \
  mv GEM-binaries-*/bin/* /usr/local/bin/ && rm -rf GEM*

  #############################################################################
  # TADbit
  wget --quiet --no-check-certificate https://github.com/fransua/TADbit/archive/dev.zip && unzip dev.zip && \
  cd TADbit-dev && python setup.py install && cd .. && rm -rf TADbit-dev dev.zip && \
  apt-get remove -y --purge unzip build-essential && \
  apt-get autoremove -y && \
  apt-get autoclean -y && \
  rm -rf /var/lib/apt/lists/*

%runscript
  echo "Wecome to TADbit Singularity container"
  exec /bin/bash --norc
  # to run jupyter the notebok has to be built and installed as writable (with sudo)
  # echo "Starting notebook..."
  # echo "Open browser to localhost:8888"
  # exec /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --allow-root --port=8888 --no-browser
