OBJECTS = tadbit.o tadbit_R.o _pytadbit.so pytadbit.pyc

all: _pytadbit.so

clean:
	rm -f $(OBJECTS)
	rm -rf build/

_pytadbit.so: pytadbit_wrap.c
	python setup.py build_ext --inplace

tadbit.o: tadbit.c
	gcc -fnested-functions -std=gnu99 -fPIC -g -O3 -c tadbit.c \
		-lpthread -Wall

pytadbit_wrap.c: pytadbit.i tadbit.c
	swig -python pytadbit.i
